### ISSUE TITLE
Incorrect parameter description/type for config properties

### ISSUE THREAD

**Issue by fnordahl** [openstack-charmers/charm-mysql-innodb-cluster#1]
Hey @thedac I came across this while reading through the new charm code and thought it deserved some feedback.

https://github.com/openstack-charmers/charm-mysql-innodb-cluster/blob/c1fbc3c86a656674ff270c987af933b633f66236/src/lib/charm/mysql_innodb_cluster.py#L36-L41

What `charms.openstack` actually pass in is a `charms_openstack.adapters.ConfigurationAdapter` derived class.  You can get to the charm instance by accessing the `charm_instance` property, i.e. `cls.charm_instance.my_method()`

The variable does not currently appear to be used by the custom config properties, which is totally fine, but I think it would be good to have the docstring right for future travellers.

**Comment by thedac** [comment]
Fix in gerrit https://review.opendev.org/#/c/693581/

**Comment by fnordahl** [comment]
Thx!
